### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by eXale1n** [pauldstar/reactive-field#2]
Hey!

Loving the additions, exactly what I was looking for.
However, the ReactHasManyField has multiple mixins that are missing.

`
import AddResource from "@ui/mixins/ResourceCrud";
import FormFieldStatus from "@ui/mixins/FormFieldStatus";
import Tabs from "@ui/components/tabs/Tabs";
import Tab from "@ui/components/tabs/Tab";
`

Can you tell me where I can find those?
Thanks

**Comment by pauldstar** [comment]
@eXale1n Hey, you'll find them here: https://github.com/pauldstar/nova-compact-ui

It has a ReadMe, but I haven't worked on these in a long while (moved jobs), so you'll have to figure out the rest I'm afraid.

Glad this has helped you a little bit :) Thanks

**Comment by eXale1n** [comment]
Thank you!
